//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_63130260.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_line()
        {
            this.user_review = new HashSet<user_review>();
        }
    
        public int id { get; set; }
        public Nullable<int> product_item_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public Nullable<bool> reviewed { get; set; }
    
        public virtual shop_order shop_order { get; set; }
        public virtual product_item product_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_review> user_review { get; set; }
    }
}
