//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_63130260.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.product_item = new HashSet<product_item>();
        }
    
        public int id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string product_image { get; set; }
    
        public virtual product_category product_category { get; set; }
        public virtual product_attributes product_attributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_item> product_item { get; set; }
    }
}
