//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_63130260.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_item()
        {
            this.order_line = new HashSet<order_line>();
            this.shopping_cart_item = new HashSet<shopping_cart_item>();
        }
    
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> qty_received { get; set; }
        public Nullable<int> qty_in_stock { get; set; }
        public Nullable<int> qty_sold { get; set; }
        public string product_image { get; set; }
        public Nullable<decimal> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_line> order_line { get; set; }
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shopping_cart_item> shopping_cart_item { get; set; }
    }
}
