//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_63130260.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion
    {
        public int id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual product_category product_category { get; set; }
    }
}
