//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_63130260.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shop_order()
        {
            this.order_line = new HashSet<order_line>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string order_first_name { get; set; }
        public string order_last_name { get; set; }
        public string order_phone { get; set; }
        public Nullable<int> payment_method_id { get; set; }
        public Nullable<int> shipping_address { get; set; }
        public Nullable<int> shipping_method { get; set; }
        public Nullable<decimal> order_total { get; set; }
        public Nullable<bool> order_status { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string order_note { get; set; }
    
        public virtual address address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_line> order_line { get; set; }
        public virtual payment_type payment_type { get; set; }
        public virtual shipping_method shipping_method1 { get; set; }
        public virtual site_user site_user { get; set; }
    }
}
