//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_63130260.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopping_cart_item
    {
        public int id { get; set; }
        public Nullable<int> cart_id { get; set; }
        public Nullable<int> product_item_id { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual product_item product_item { get; set; }
        public virtual shopping_cart shopping_cart { get; set; }
    }
}
