//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_63130260.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_address
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> address_id { get; set; }
        public Nullable<bool> is_default { get; set; }
    
        public virtual address address { get; set; }
        public virtual site_user site_user { get; set; }
    }
}
